[package]
name = "ngu_script"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
screenshots = "0.3.0"
imageproc = "0.23.0"
image = "0.24.2"
enigo = "0.0.14"